"""agent delivery outbox

Revision ID: 1022d2d38749
Revises: d8985d024e68
Create Date: 2026-07-13 03:44:17.586746

"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = '1022d2d38749'
down_revision = 'd8985d024e68'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_deliveries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event', sa.String(length=80), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'delivered', 'exhausted', name='webhookdeliverystatus', native_enum=False, length=30), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_deliveries_next_attempt_at'), ['next_attempt_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_deliveries_next_attempt_at'))

    op.drop_table('agent_deliveries')
    # ### end Alembic commands ###
