"""agents and tenant scoping

Revision ID: 360818341447
Revises: 1022d2d38749
Create Date: 2026-07-13 04:25:07.825591

"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = '360818341447'
down_revision = '1022d2d38749'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('webhook_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agents_key_hash'), ['key_hash'], unique=True)

    with op.batch_alter_table('agent_deliveries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agent_id', sa.Uuid(), nullable=True))
        batch_op.create_index(batch_op.f('ix_agent_deliveries_agent_id'), ['agent_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_agent_deliveries_agent_id_agents', 'agents', ['agent_id'], ['id']
        )

    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agent_id', sa.Uuid(), nullable=True))
        batch_op.create_index(batch_op.f('ix_contacts_agent_id'), ['agent_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_contacts_agent_id_agents', 'agents', ['agent_id'], ['id']
        )

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agent_id', sa.Uuid(), nullable=True))
        batch_op.create_index(batch_op.f('ix_conversations_agent_id'), ['agent_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_conversations_agent_id_agents', 'agents', ['agent_id'], ['id']
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_constraint('fk_conversations_agent_id_agents', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_conversations_agent_id'))
        batch_op.drop_column('agent_id')

    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_contacts_agent_id_agents', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_contacts_agent_id'))
        batch_op.drop_column('agent_id')

    with op.batch_alter_table('agent_deliveries', schema=None) as batch_op:
        batch_op.drop_constraint('fk_agent_deliveries_agent_id_agents', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_agent_deliveries_agent_id'))
        batch_op.drop_column('agent_id')

    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agents_key_hash'))

    op.drop_table('agents')
    # ### end Alembic commands ###
