"""initial schema

Revision ID: 708a479e142c
Revises: 
Create Date: 2026-07-02 09:08:29.076634

"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = '708a479e142c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('channel_identities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.Enum('sms', 'email', 'voice', name='channeltype', native_enum=False, length=30), nullable=False),
    sa.Column('address', sa.String(length=320), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('channel_identities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_channel_identities_address'), ['address'], unique=False)
        batch_op.create_index(batch_op.f('ix_channel_identities_contact_id'), ['contact_id'], unique=False)

    op.create_table('conversations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('active', 'paused', 'closed', name='conversationstatus', native_enum=False, length=30), nullable=False),
    sa.Column('current_channel', sa.Enum('sms', 'email', 'voice', name='channeltype', native_enum=False, length=30), nullable=False),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversations_contact_id'), ['contact_id'], unique=False)

    op.create_table('channel_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.Enum('sms', 'email', 'voice', name='channeltype', native_enum=False, length=30), nullable=False),
    sa.Column('state', sa.Enum('open', 'closed', name='sessionstate', native_enum=False, length=30), nullable=False),
    sa.Column('session_meta', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('channel_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_channel_sessions_conversation_id'), ['conversation_id'], unique=False)

    op.create_table('conversation_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('message', 'channel_switch', 'escalation', 'timeout', 'note', name='eventtype', native_enum=False, length=30), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversation_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_events_conversation_id'), ['conversation_id'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('direction', sa.Enum('inbound', 'outbound', name='direction', native_enum=False, length=30), nullable=False),
    sa.Column('channel', sa.Enum('sms', 'email', 'voice', name='channeltype', native_enum=False, length=30), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('channel_meta', sa.JSON(), nullable=False),
    sa.Column('delivery_status', sa.Enum('queued', 'sent', 'delivered', 'failed', 'read', name='deliverystatus', native_enum=False, length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_conversation_id'), ['conversation_id'], unique=False)

    op.create_table('follow_ups',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('message_id', sa.Uuid(), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('pending', 'fired', 'cancelled', name='followupstatus', native_enum=False, length=30), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('follow_ups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_follow_ups_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_follow_ups_due_at'), ['due_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follow_ups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_follow_ups_due_at'))
        batch_op.drop_index(batch_op.f('ix_follow_ups_conversation_id'))

    op.drop_table('follow_ups')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_conversation_id'))

    op.drop_table('messages')
    with op.batch_alter_table('conversation_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_events_conversation_id'))

    op.drop_table('conversation_events')
    with op.batch_alter_table('channel_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_channel_sessions_conversation_id'))

    op.drop_table('channel_sessions')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_contact_id'))

    op.drop_table('conversations')
    with op.batch_alter_table('channel_identities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_channel_identities_contact_id'))
        batch_op.drop_index(batch_op.f('ix_channel_identities_address'))

    op.drop_table('channel_identities')
    op.drop_table('contacts')
    # ### end Alembic commands ###
