"""add opted_out to channel identities

Revision ID: 8639bf20aaf3
Revises: 708a479e142c
Create Date: 2026-07-02 18:49:19.265533

"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = '8639bf20aaf3'
down_revision = '708a479e142c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('channel_identities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('opted_out', sa.Boolean(), server_default=sa.false(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('channel_identities', schema=None) as batch_op:
        batch_op.drop_column('opted_out')

    # ### end Alembic commands ###
