"""unique channel identity address

Revision ID: d8985d024e68
Revises: 8639bf20aaf3
Create Date: 2026-07-07 04:07:45.192160

"""
from __future__ import annotations

from alembic import op

revision = 'd8985d024e68'
down_revision = '8639bf20aaf3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('channel_identities', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_channel_identity_address', ['channel', 'address'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('channel_identities', schema=None) as batch_op:
        batch_op.drop_constraint('uq_channel_identity_address', type_='unique')

    # ### end Alembic commands ###
